### ISSUE TITLE
Mistake of this line of code?

### ISSUE THREAD

**Issue by p-null** [binzhouchn/capsule-pytorch#1]
Hi, thanks for your work!
The output of `nn.gru` has shape (seq_len, batch_size, num_dirct*h)
While [this line](https://github.com/binzhouchn/capsule-pytorch/blob/74b2a2e5e642ce448e0cebb097e35a8834138c70/capsule_layer.py#L104) take the first element of shape as batch size, which is actually not the case?
Any thoughts?

**Comment by binzhouchn** [comment]
the actual output shape like (batch_size, seq_len, num_dirct*h), mistake in docs
